### ISSUE TITLE
Domino container not coming up

### ISSUE THREAD

**Issue by srujansagi** [IBM/domino-docker#45]
I'm seeing below error when deploying domino12_auto_config.yml
```
Error: failed to start container "domino12": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/local/start.sh\": stat /local/start.sh: no such file or directory": unknown
```

 ``` 
    volumeMounts:
    - name: domino-data
      mountPath: /local

  volumes:
  - name: domino-data
    persistentVolumeClaim:
      claimName: local-path-pvc

  - name: domino-cfg
    configMap:
      name: domino12-cfg
   ```

I have created the docker12 image using the tar file provided by HCL and i can see the /local has start.sh script in the image 

```
docker exec -it 8a6a6bd8b4cb sh
sh-4.4$ ls -l /local        
total 28
-rwxr-xr-x  1 root  root 1330 Jun  4  2021 healthcheck.sh
drwx------  1 notes root 4096 Mar 18 19:01 notes
drwxrwxr-x 13 notes root 4096 Mar 18 18:30 notesdata
-rwxr-xr-x  1 root  root 1199 Jun  4  2021 sample.sh
drwxr-xr-x  2 root  root 4096 Jun  4  2021 start.d
-rwxr-xr-x  1 root  root 5335 Jun  4  2021 start.sh
sh-4.4$ 
```

I'm actually helping containerizing the domino application for a team and this is the only repo i found online with some details around domino app. Thank you for contributing to the community.

Any help regarding above issue would really greatful.
